openapi: 3.1.0
info:
  contact:
    email: support@lithic.com
  description: 'The Lithic Developer API is designed to provide a predictable programmatic interface for accessing your Lithic account through an API and transaction webhooks.

    Note that your API key is a secret and should be treated as such. Don''t share it with anyone, including us. We will never ask you for it.

    '
  termsOfService: https://lithic.com/legal/terms
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.txt
  title: Lithic Developer 3DS Tokenization API
  version: 1.0.0
servers:
- description: Sandbox environment that provides key functionality mirroring production
  url: https://sandbox.lithic.com
security:
- ApiKeyAuth: []
tags:
- name: Tokenization
paths:
  /v1/digital_card_art:
    get:
      description: List digital card art.
      operationId: getDigitalCardArt
      parameters:
      - $ref: '#/components/parameters/endingBefore'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/startingAfter'
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  data:
                    items:
                      $ref: '#/components/schemas/DigitalCardArt'
                    type: array
                  has_more:
                    description: More data exists.
                    type: boolean
                required:
                - data
                - has_more
                type: object
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '429':
          $ref: '#/components/responses/TooManyRequests'
      summary: List digital card art
      tags:
      - Tokenization
  /v1/digital_card_art/{digital_card_art_token}:
    get:
      description: Get digital card art by token.
      operationId: getDigitalCardArtByToken
      parameters:
      - description: Specifies the digital card art to be displayed in the user’s digital wallet after tokenization. This artwork must be approved by Mastercard and configured by Lithic to use. See [Flexible Card Art Guide](https://docs.lithic.com/docs/about-digital-wallets#flexible-card-art).
        in: path
        name: digital_card_art_token
        required: true
        schema:
          format: uuid
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DigitalCardArt'
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '429':
          $ref: '#/components/responses/TooManyRequests'
      summary: Get digital card art by token
      tags:
      - Tokenization
  /v1/simulate/tokenizations:
    post:
      description: 'This endpoint is used to simulate a card''s tokenization in the Digital Wallet and merchant tokenization ecosystem.

        '
      operationId: postSimulateTokenizations
      requestBody:
        content:
          application/json:
            examples:
              simulateTokenizations:
                summary: Simulates a card's tokenization
                value:
                  account_score: 5
                  cvv: '776'
                  device_score: 5
                  expiration_date: 08/29
                  pan: '4111111289144142'
                  tokenization_source: APPLE_PAY
                  wallet_recommended_decision: APPROVED
            schema:
              properties:
                account_score:
                  default: 5
                  description: The account score (1-5) that represents how the Digital Wallet's view on how reputable an end user's account is.
                  type: integer
                cvv:
                  description: The three digit cvv for the card.
                  example: '776'
                  maxLength: 3
                  minLength: 3
                  type: string
                device_score:
                  default: 5
                  description: The device score (1-5) that represents how the Digital Wallet's view on how reputable an end user's device is.
                  type: integer
                entity:
                  description: Optional field to specify the token requestor name for a merchant token simulation. Ignored when tokenization_source is not MERCHANT.
                  type: string
                expiration_date:
                  description: The expiration date of the card in 'MM/YY' format.
                  maxLength: 5
                  minLength: 5
                  type: string
                pan:
                  description: The sixteen digit card number.
                  example: '4111111289144142'
                  maxLength: 16
                  minLength: 16
                  type: string
                tokenization_source:
                  description: The source of the tokenization request.
                  enum:
                  - APPLE_PAY
                  - GOOGLE
                  - SAMSUNG_PAY
                  - MERCHANT
                  type: string
                wallet_recommended_decision:
                  default: APPROVED
                  description: The decision that the Digital Wallet's recommend
                  enum:
                  - APPROVED
                  - DECLINED
                  - REQUIRE_ADDITIONAL_AUTHENTICATION
                  type: string
              required:
              - cvv
              - expiration_date
              - pan
              - tokenization_source
              type: object
        required: true
      responses:
        '201':
          content:
            application/json:
              example:
                account_token: 61c3acef-3c2c-4d61-9352-941397b92ca3
                card_token: 16a410c9-7f5c-43e9-8108-bb8a72c063f7
                created_at: '2023-08-28T15:57:14.578051'
                events:
                - created_at: '2023-09-13T16:01:13.643241'
                  result: TOKEN_ACTIVATED
                  token: a690b617-d3d4-4976-82f6-901f817ad98a
                  type: TOKENIZATION_UPDATED
                - created_at: '2023-09-13T16:01:13.643241'
                  result: APPROVED
                  token: 2b2a1038-45f3-42e4-98bb-e745be3f1de1
                  type: TOKENIZATION_AUTHORIZATION
                status: ACTIVE
                token: 3e9a10da-11be-4a62-a510-d43548bfcec1
                tokenization_channel: DIGITAL_WALLET
                token_requestor_name: APPLE_PAY
                token_unique_reference: DM4MMC0000332872ef1029f38fa0184b5c9260383da192b22
                dpan: '5489123487251234'
                payment_account_reference_id: 50019T0AL7DEFGJ4AGGT8BQDOABCD
                updated_at: '2023-08-28T15:57:14.578051'
              schema:
                $ref: '#/components/schemas/tokenization'
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '429':
          $ref: '#/components/responses/TooManyRequests'
      summary: Simulate a card's tokenization
      tags:
      - Tokenization
  /v1/tokenization_decisioning/secret:
    get:
      description: 'Retrieve the Tokenization Decisioning secret key. If one does not exist your program yet, calling this endpoint will create one for you. The headers of the Tokenization Decisioning request will contain a hmac signature which you can use to verify requests originate from Lithic. See [this page](https://docs.lithic.com/docs/events-api#verifying-webhooks) for more detail about verifying Tokenization Decisioning requests.

        '
      operationId: getTokenizationDecisioningSecret
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  secret:
                    description: The Tokenization Decisioning HMAC secret
                    example: whsec_1NDsYinMGr951KuDEaj78VtWzlyPaOnwUVagFiWIPJs=
                    type: string
                type: object
          description: OK
        '401':
          $ref: '#/components/responses/Unauthorized'
        '429':
          $ref: '#/components/responses/TooManyRequests'
      summary: Retrieve the Tokenization Decisioning HMAC secret key
      tags:
      - Tokenization
  /v1/tokenization_decisioning/secret/rotate:
    post:
      description: 'Generate a new Tokenization Decisioning secret key. The old Tokenization Decisioning secret key will be deactivated 24 hours after a successful request to this endpoint.

        '
      operationId: rotateTokenizationDecisioningSecret
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  secret:
                    description: The new Tokenization Decisioning HMAC secret
                    example: whsec_1NDsYinMGr951KuDEaj78VtWzlyPaOnwUVagFiWIPJs=
                    type: string
                type: object
          description: OK
        '401':
          $ref: '#/components/responses/Unauthorized'
        '429':
          $ref: '#/components/responses/TooManyRequests'
      summary: Rotate the Tokenization Decisioning HMAC secret key
      tags:
      - Tokenization
  /v1/tokenizations:
    get:
      description: List card tokenizations
      operationId: getTokenizations
      parameters:
      - description: Filters for tokenizations associated with a specific account.
        in: query
        name: account_token
        schema:
          format: uuid
          type: string
      - description: Filter for tokenizations created after this date.
        in: query
        name: begin
        schema:
          format: date
          type: string
      - description: Filters for tokenizations associated with a specific card.
        in: query
        name: card_token
        schema:
          format: uuid
          type: string
      - description: Filter for tokenizations created before this date.
        in: query
        name: end
        schema:
          format: date
          type: string
      - description: Filter for tokenizations by tokenization channel. If this is not specified, only DIGITAL_WALLET tokenizations will be returned.
        in: query
        name: tokenization_channel
        schema:
          enum:
          - DIGITAL_WALLET
          - MERCHANT
          - ALL
          type: string
      - $ref: '#/components/parameters/endingBefore'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/startingAfter'
      responses:
        '200':
          content:
            application/json:
              example:
                data:
                - account_token: 61c3acef-3c2c-4d61-9352-941397b92ca3
                  card_token: 16a410c9-7f5c-43e9-8108-bb8a72c063f7
                  created_at: '2023-08-28T15:57:14.578051'
                  events:
                  - created_at: '2023-09-13T16:01:13.643241'
                    result: TOKEN_ACTIVATED
                    token: a690b617-d3d4-4976-82f6-901f817ad98a
                    type: TOKENIZATION_UPDATED
                  - created_at: '2023-09-13T16:01:13.643241'
                    result: APPROVED
                    token: 2b2a1038-45f3-42e4-98bb-e745be3f1de1
                    type: TOKENIZATION_AUTHORIZATION
                    tokenization_decline_reasons: []
                    tokenization_tfa_reasons: []
                    rule_results: []
                  status: ACTIVE
                  token: 3e9a10da-11be-4a62-a510-d43548bfcec1
                  token_requestor_name: APPLE_PAY
                  token_unique_reference: DM4MMC0000332872ef1029f38fa0184b5c9260383da192b22
                  tokenization_channel: DIGITAL_WALLET
                  dpan: '5489123487251234'
                  device_id: ba6f05c312d4a5789b2e04f05c1f9d3b81GJ4AG1
                  payment_account_reference_id: 50019T0AL7DEFGJ4AGGT8BQDOABCD
                  updated_at: '2023-08-28T15:57:14.578051'
                has_more: false
              schema:
                properties:
                  data:
                    items:
                      $ref: '#/components/schemas/tokenization'
                    type: array
                  has_more:
                    type: boolean
                type: object
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '429':
          $ref: '#/components/responses/TooManyRequests'
      summary: Get a card's tokenizations
      tags:
      - Tokenization
  /v1/tokenizations/{tokenization_token}:
    get:
      description: Get tokenization
      operationId: getTokenization
      parameters:
      - description: Tokenization token
        in: path
        name: tokenization_token
        required: true
        schema:
          format: uuid
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
                account_token: 61c3acef-3c2c-4d61-9352-941397b92ca3
                card_token: 16a410c9-7f5c-43e9-8108-bb8a72c063f7
                created_at: '2023-08-28T15:57:14.578051'
                events:
                - created_at: '2023-09-13T16:01:13.643241'
                  result: TOKEN_ACTIVATED
                  token: a690b617-d3d4-4976-82f6-901f817ad98a
                  type: TOKENIZATION_UPDATED
                - created_at: '2023-09-13T16:01:13.643241'
                  result: APPROVED
                  token: 2b2a1038-45f3-42e4-98bb-e745be3f1de1
                  type: TOKENIZATION_AUTHORIZATION
                  tokenization_decline_reasons: []
                  tokenization_tfa_reasons: []
                  rule_results: []
                status: ACTIVE
                token: 3e9a10da-11be-4a62-a510-d43548bfcec1
                token_requestor_name: APPLE_PAY
                token_unique_reference: DM4MMC0000332872ef1029f38fa0184b5c9260383da192b22
                tokenization_channel: DIGITAL_WALLET
                dpan: '5489123487251234'
                device_id: ba6f05c312d4a5789b2e04f05c1f9d3b81GJ4AG1
                payment_account_reference_id: 50019T0AL7DEFGJ4AGGT8BQDOABCD
                updated_at: '2023-08-28T15:57:14.578051'
              schema:
                $ref: '#/components/schemas/tokenization'
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '429':
          $ref: '#/components/responses/TooManyRequests'
      summary: Get a single card tokenization
      tags:
      - Tokenization
  /v1/tokenizations/{tokenization_token}/pause:
    post:
      description: 'This endpoint is used to ask the card network to pause a tokenization. A successful response indicates that the request was successfully delivered to the card network. When the card network pauses the tokenization, the state will be updated and a tokenization.updated event will be sent. The endpoint may only be used on tokenizations with status `ACTIVE`.

        A paused token will prevent merchants from sending authorizations, and is a temporary status that can be changed.

        Reach out at [lithic.com/contact](https://lithic.com/contact) for more information.'
      operationId: pauseTokenization
      parameters:
      - description: Tokenization token
        in: path
        name: tokenization_token
        required: true
        schema:
          format: uuid
          type: string
      responses:
        '200':
          content: {}
          description: Pause tokenization request successfully delivered to the card network.
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '429':
          $ref: '#/components/responses/TooManyRequests'
      summary: Pause a card tokenization
      tags:
      - Tokenization
  /v1/tokenizations/{tokenization_token}/unpause:
    post:
      description: 'This endpoint is used to ask the card network to unpause a tokenization. A successful response indicates that the request was successfully delivered to the card network. When the card network unpauses the tokenization, the state will be updated and a tokenization.updated event will be sent. The endpoint may only be used on tokenizations with status `PAUSED`.

        This will put the tokenization in an active state, and transactions may resume.

        Reach out at [lithic.com/contact](https://lithic.com/contact) for more information.'
      operationId: unpauseTokenization
      parameters:
      - description: Tokenization token
        in: path
        name: tokenization_token
        required: true
        schema:
          format: uuid
          type: string
      responses:
        '200':
          content: {}
          description: Unpause tokenization request successfully delivered to the card network.
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '429':
          $ref: '#/components/responses/TooManyRequests'
      summary: Unpause a card tokenization
      tags:
      - Tokenization
  /v1/tokenizations/{tokenization_token}/deactivate:
    post:
      description: 'This endpoint is used to ask the card network to deactivate a tokenization. A successful response indicates that the request was successfully delivered to the card network. When the card network deactivates the tokenization, the state will be updated and a tokenization.updated event will be sent.

        Authorizations attempted with a deactivated tokenization will be blocked and will not be forwarded to Lithic from the network. Deactivating the token is a permanent operation. If the target is a digital wallet tokenization, it will be removed from its device.

        Reach out at [lithic.com/contact](https://lithic.com/contact) for more information.'
      operationId: deactivateTokenization
      parameters:
      - description: Tokenization token
        in: path
        name: tokenization_token
        required: true
        schema:
          format: uuid
          type: string
      responses:
        '200':
          content: {}
          description: Deactivate tokenization request successfully delivered to the card network.
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '429':
          $ref: '#/components/responses/TooManyRequests'
      summary: Deactivate a card tokenization
      tags:
      - Tokenization
  /v1/tokenizations/{tokenization_token}/activate:
    post:
      description: 'This endpoint is used to ask the card network to activate a tokenization. A successful response indicates that the request was successfully delivered to the card network. When the card network activates the tokenization, the state will be updated and a tokenization.updated event will be sent. The endpoint may only be used on digital wallet tokenizations with status `INACTIVE`, `PENDING_ACTIVATION`, or `PENDING_2FA`.

        This will put the tokenization in an active state, and transactions will be allowed.

        Reach out at [lithic.com/contact](https://lithic.com/contact) for more information.'
      operationId: activateTokenization
      parameters:
      - description: Tokenization token
        in: path
        name: tokenization_token
        required: true
        schema:
          format: uuid
          type: string
      responses:
        '200':
          content: {}
          description: Activate tokenization request successfully delivered to the card network.
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '429':
          $ref: '#/components/responses/TooManyRequests'
      summary: Activate a card tokenization
      tags:
      - Tokenization
  /v1/tokenizations/{tokenization_token}/resend_activation_code:
    post:
      description: 'This endpoint is used to ask the card network to send another activation code to a cardholder that has already tried tokenizing a card. A successful response indicates that the request was successfully delivered to the card network.

        The endpoint may only be used on Mastercard digital wallet tokenizations with status `INACTIVE`, `PENDING_ACTIVATION`, or `PENDING_2FA`. The network will send a new activation code to the one of the contact methods provided in the initial tokenization flow. If a user fails to enter the code correctly 3 times, the contact method will not be eligible for resending the activation code, and the cardholder must restart the provision process.

        Reach out at [lithic.com/contact](https://lithic.com/contact) for more information.'
      operationId: resendActivationCodeForTokenization
      parameters:
      - description: Tokenization token
        in: path
        name: tokenization_token
        required: true
        schema:
          format: uuid
          type: string
      requestBody:
        content:
          application/json:
            examples:
              resendActivationCodeSms:
                summary: Resend activation code to SMS contact method
                value:
                  activation_method_type: TEXT_TO_CARDHOLDER_NUMBER
            schema:
              properties:
                activation_method_type:
                  description: 'The communication method that the user has selected to use to receive the authentication code.

                    Supported Values: Sms = "TEXT_TO_CARDHOLDER_NUMBER". Email = "EMAIL_TO_CARDHOLDER_ADDRESS"'
                  enum:
                  - EMAIL_TO_CARDHOLDER_ADDRESS
                  - TEXT_TO_CARDHOLDER_NUMBER
                  type: string
      responses:
        '200':
          content: {}
          description: Resend activation code request successfully delivered to the card network.
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '429':
          $ref: '#/components/responses/TooManyRequests'
      summary: Resend activation code for a card tokenization
      tags:
      - Tokenization
  /v1/tokenizations/{tokenization_token}/update_digital_card_art:
    post:
      description: 'This endpoint is used update the digital card art for a digital wallet tokenization. A successful response indicates that the card network has updated the tokenization''s art, and the tokenization''s `digital_cart_art_token` field was updated.

        The endpoint may not be used on tokenizations with status `DEACTIVATED`.

        Note that this updates the art for one specific tokenization, not all tokenizations for a card. New tokenizations for a card will be created with the art referenced in the card object''s `digital_card_art_token` field.

        Reach out at [lithic.com/contact](https://lithic.com/contact) for more information.'
      operationId: updateDigitalCardArtForTokenization
      parameters:
      - description: Tokenization token
        in: path
        name: tokenization_token
        required: true
        schema:
          format: uuid
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                digital_card_art_token:
                  description: Specifies the digital card art to be displayed in the user’s digital wallet for a tokenization. This artwork must be approved by the network and configured by Lithic to use. See [Flexible Card Art Guide](https://docs.lithic.com/docs/about-digital-wallets#flexible-card-art).
                  example: 5e9483eb-8103-4e16-9794-2106111b2eca
                  format: uuid
                  type: string
      responses:
        '200':
          content:
            application/json:
              example:
                account_token: 61c3acef-3c2c-4d61-9352-941397b92ca3
                card_token: 16a410c9-7f5c-43e9-8108-bb8a72c063f7
                created_at: '2023-08-28T15:57:14.578051'
                digital_card_art_token: 0ca42d08-12ae-4bc6-bd00-787e6df53cff
                events:
                - created_at: '2023-09-13T16:01:13.643241'
                  result: TOKEN_ACTIVATED
                  token: a690b617-d3d4-4976-82f6-901f817ad98a
                  type: TOKENIZATION_UPDATED
                - created_at: '2023-09-13T16:01:13.643241'
                  result: APPROVED
                  token: 2b2a1038-45f3-42e4-98bb-e745be3f1de1
                  type: TOKENIZATION_AUTHORIZATION
                status: ACTIVE
                token: 3e9a10da-11be-4a62-a510-d43548bfcec1
                token_requestor_name: APPLE_PAY
                token_unique_reference: DM4MMC0000332872ef1029f38fa0184b5c9260383da192b22
                dpan: '5489123487251234'
                device_id: ba6f05c312d4a5789b2e04f05c1f9d3b81GJ4AG1
                payment_account_reference_id: 50019T0AL7DEFGJ4AGGT8BQDOABCD
                updated_at: '2023-08-28T15:57:14.578051'
                tokenization_channel: DIGITAL_WALLET
              schema:
                $ref: '#/components/schemas/tokenization'
          description: Card art successfully updated at the network and Lithic levels.
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '429':
          $ref: '#/components/responses/TooManyRequests'
      summary: Update digital card art for a card tokenization
      tags:
      - Tokenization
components:
  schemas:
    tokenization-event:
      title: Tokenization Event
      properties:
        created_at:
          description: Date and time when the tokenization event first occurred. UTC time zone.
          format: date-time
          type: string
        result:
          $ref: '#/components/schemas/tokenization-event-outcome'
        token:
          description: Globally unique identifier for a Tokenization Event
          format: uuid
          type: string
        type:
          description: Enum representing the type of tokenization event that occurred
          enum:
          - TOKENIZATION_2FA
          - TOKENIZATION_AUTHORIZATION
          - TOKENIZATION_DECISIONING
          - TOKENIZATION_ELIGIBILITY_CHECK
          - TOKENIZATION_UPDATED
          type: string
        tokenization_decline_reasons:
          description: List of reasons why the tokenization was declined
          type: array
          items:
            $ref: '#/components/schemas/tokenization-decline-reason'
        tokenization_tfa_reasons:
          description: List of reasons why two-factor authentication was required
          type: array
          items:
            $ref: '#/components/schemas/tokenization-tfa-reason'
        rule_results:
          description: Results from rules that were evaluated for this tokenization
          type: array
          items:
            $ref: '#/components/schemas/tokenization-rule-result'
    error:
      type: object
      properties:
        debugging_request_id:
          type: string
          format: uuid
          description: Identifier to help debug an error.
        message:
          type: string
          description: Explanation of error response.
      required:
      - debugging_request_id
      - message
    tokenization-event-outcome:
      title: Tokenization Event Outcome
      description: Enum representing the result of the tokenization event
      type: string
      enum:
      - APPROVED
      - DECLINED
      - NOTIFICATION_DELIVERED
      - REQUIRE_ADDITIONAL_AUTHENTICATION
      - TOKEN_ACTIVATED
      - TOKEN_CREATED
      - TOKEN_DEACTIVATED
      - TOKEN_DELETED_FROM_CONSUMER_APP
      - TOKEN_INACTIVE
      - TOKEN_STATE_UNKNOWN
      - TOKEN_SUSPENDED
      - TOKEN_UPDATED
    tokenization:
      title: Tokenization
      properties:
        account_token:
          description: The account token associated with the card being tokenized.
          format: uuid
          type: string
        card_token:
          description: The card token associated with the card being tokenized.
          format: uuid
          type: string
        created_at:
          description: Date and time when the tokenization first occurred. UTC time zone.
          format: date-time
          type: string
        device_id:
          description: The device identifier associated with the tokenization.
          type:
          - string
          - 'null'
        digital_card_art_token:
          description: Specifies the digital card art displayed in the user's digital wallet after tokenization. This will be null if the tokenization was created without an associated digital card art. See [Flexible Card Art Guide](https://docs.lithic.com/docs/about-digital-wallets#flexible-card-art).
          format: uuid
          type:
          - string
          - 'null'
        events:
          description: A list of events related to the tokenization.
          items:
            $ref: '#/components/schemas/tokenization-event'
          type: array
        status:
          description: The status of the tokenization request
          enum:
          - ACTIVE
          - DEACTIVATED
          - INACTIVE
          - PAUSED
          - PENDING_2FA
          - PENDING_ACTIVATION
          - UNKNOWN
          type: string
        token:
          description: Globally unique identifier for a Tokenization
          format: uuid
          type: string
        token_requestor_name:
          description: The entity that requested the tokenization. For digital wallets, this will be one of the defined wallet types. For merchant tokenizations, this will be a free-form merchant name string.
          anyOf:
          - title: Digital wallet type
            description: Digital wallet type
            enum:
            - AMAZON_ONE
            - ANDROID_PAY
            - APPLE_PAY
            - FACEBOOK
            - FITBIT_PAY
            - GARMIN_PAY
            - GOOGLE_PAY
            - MICROSOFT_PAY
            - NETFLIX
            - SAMSUNG_PAY
            - UNKNOWN
            - VISA_CHECKOUT
            type: string
          - title: Merchant name
            description: Merchant name for merchant tokenizations
            type: string
        token_unique_reference:
          description: The network's unique reference for the tokenization.
          type: string
        dpan:
          description: The dynamic pan assigned to the token by the network.
          type:
          - string
          - 'null'
        payment_account_reference_id:
          description: The network's unique reference for the card that is tokenized.
          type:
          - string
          - 'null'
        tokenization_channel:
          description: The channel through which the tokenization was made.
          enum:
          - DIGITAL_WALLET
          - MERCHANT
          type: string
        updated_at:
          description: Latest date and time when the tokenization was updated. UTC time zone.
          format: date-time
          type: string
      required:
      - account_token
      - card_token
      - created_at
      - status
      - token
      - token_requestor_name
      - token_unique_reference
      - dpan
      - tokenization_channel
      - updated_at
      type: object
    DigitalCardArt:
      properties:
        card_program_token:
          description: Globally unique identifier for the card program.
          format: uuid
          type: string
        created:
          description: Timestamp of when card art was created.
          format: date-time
          type: string
        description:
          description: Description of the card art.
          type: string
        is_card_program_default:
          description: Whether the card art is the default card art to be added upon tokenization.
          type: boolean
        is_enabled:
          description: Whether the card art is enabled.
          type: boolean
        network:
          description: Card network.
          enum:
          - MASTERCARD
          - VISA
          type: string
        token:
          description: Globally unique identifier for the card art.
          format: uuid
          type: string
      required:
      - card_program_token
      - created
      - description
      - is_enabled
      - network
      - token
      type: object
    tokenization-decline-reason:
      title: Tokenization Decline Reason
      description: Reason code for why a tokenization was declined
      type: string
      enum:
      - ACCOUNT_SCORE_1
      - DEVICE_SCORE_1
      - ALL_WALLET_DECLINE_REASONS_PRESENT
      - WALLET_RECOMMENDED_DECISION_RED
      - CVC_MISMATCH
      - CARD_EXPIRY_MONTH_MISMATCH
      - CARD_EXPIRY_YEAR_MISMATCH
      - CARD_INVALID_STATE
      - CUSTOMER_RED_PATH
      - INVALID_CUSTOMER_RESPONSE
      - NETWORK_FAILURE
      - GENERIC_DECLINE
      - DIGITAL_CARD_ART_REQUIRED
    tokenization-rule-result:
      title: Tokenization Rule Result
      type: object
      properties:
        auth_rule_token:
          description: The Auth Rule Token associated with the rule. If this is set to null, then the result was not associated with a customer-configured rule. This may happen in cases where a tokenization is declined or requires TFA due to a Lithic-configured security or compliance rule, for example.
          oneOf:
          - type: 'null'
          - type: string
            format: uuid
        result:
          description: The result associated with this rule
          type: string
          enum:
          - APPROVED
          - DECLINED
          - REQUIRE_TFA
          - ERROR
        name:
          description: The name for the rule, if any was configured
          oneOf:
          - type: 'null'
          - type: string
        explanation:
          description: A human-readable explanation outlining the motivation for the rule's result
          oneOf:
          - type: 'null'
          - type: string
      required:
      - auth_rule_token
      - result
      - name
      - explanation
    tokenization-tfa-reason:
      title: Tokenization TFA Reason
      description: Reason code for why a tokenization required two-factor authentication
      type: string
      enum:
      - WALLET_RECOMMENDED_TFA
      - SUSPICIOUS_ACTIVITY
      - DEVICE_RECENTLY_LOST
      - TOO_MANY_RECENT_ATTEMPTS
      - TOO_MANY_RECENT_TOKENS
      - TOO_MANY_DIFFERENT_CARDHOLDERS
      - OUTSIDE_HOME_TERRITORY
      - HAS_SUSPENDED_TOKENS
      - HIGH_RISK
      - ACCOUNT_SCORE_LOW
      - DEVICE_SCORE_LOW
      - CARD_STATE_TFA
      - HARDCODED_TFA
      - CUSTOMER_RULE_TFA
      - DEVICE_HOST_CARD_EMULATION
  parameters:
    startingAfter:
      description: A cursor representing an item's token after which a page of results should begin. Used to retrieve the next page of results after this item.
      in: query
      name: starting_after
      required: false
      schema:
        type: string
    endingBefore:
      description: A cursor representing an item's token before which a page of results should end. Used to retrieve the previous page of results before this item.
      in: query
      name: ending_before
      required: false
      schema:
        type: string
    pageSize:
      description: Page size (for pagination).
      in: query
      name: page_size
      schema:
        default: 50
        maximum: 100
        minimum: 1
        type: integer
  responses:
    Unauthorized:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: '|   |   |

        |---|---|

        | User has not been authenticated | Invalid or missing API key |

        | API key is not active | The API key used is no longer active |

        | Could not find API key | The API key provided is not associated with any user |

        | Please provide API key in Authorization header | The Authorization header is not in the request |

        | Please provide API key in the form Authorization: [api-key] | The Authorization header is not formatted properly |

        | Insufficient privileges. Issuing API key required | Write access requires an Issuing API key. Reach out at [lithic.com/contact](https://lithic.com/contact) |

        | Insufficient privileges to create virtual cards. | Creating virtual cards requires an additional privilege | Reach out at [lithic.com/contact](https://lithic.com/contact) |

        '
    BadRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: A parameter in the query given in the request does not match the valid queries for the endpoint.
    NotFound:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: The specified resource was not found.
    TooManyRequests:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: 'Client has exceeded the number of allowed requests in a given time period.


        |   |   |

        |---|---|

        | Rate limited, too many requests per second | User has exceeded their per second rate limit |

        | Rate limited, reached daily limit | User has exceeded their daily rate limit |

        | Rate limited, too many keys tried | One IP has queried too many different API keys |

        '
    Conflict:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: The request could not be completed due to a conflict with the current state of the target resource.
    UnprocessableEntity:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: Unprocessable entity.
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: Authorization
      type: apiKey
